// Generated by scripts/scrape-menu.mjs. Do not edit by hand.
window.FOOSTO_MENU = {
  "source": "https://menu.foosto.com/",
  "changedAt": "2026-09-12T05:25:04.339Z",
  "checkedAt": "2026-09-12T05:25:04.339Z",
  "count": 3,
  "items": [
    {
      "code": "68693",
      "name": "সোনালী মুরগি আলু দিয়ে ঝোল, সবজি ভাজি, চিকেন দিয়ে বুটের ডাল,নাজিরশাল চালের ভাত ,সালাত",
      "chef": "Masuma Khatun",
      "price": 192,
      "available": 9,
      "images": []
    },
    {
      "code": "69887",
      "name": "পোয়া মাছ ভুনা, আলু ভর্তা, সবজি ভাজি,বুটের ডাল চিকেন দিয়ে,নাজির শাইল চালের ভাত,সালাদ",
      "chef": "Masuma Khatun",
      "price": 171,
      "available": 4,
      "images": []
    },
    {
      "code": "71209",
      "name": "গরুর ভুঁড়ি আলু দিয়ে ভুনা, আলু ভর্তা,সবজি ভাজি, চিকেন দিয়ে বুটের ডাল,নাজির শাইল চালের ভাত,সালাদ",
      "chef": "Masuma Khatun",
      "price": 203,
      "available": 10,
      "images": [
        "static-site/img/location.png",
        "static-site/img/icon-03.png",
        "static-site/img/way.png",
        "static-site/img/app-phn-logo.png",
        "static-site/img/phn.png"
      ]
    }
  ]
};
