// Generated by scripts/scrape-menu.mjs. Do not edit by hand.
window.FOOSTO_MENU = {
  "source": "https://menu.foosto.com/",
  "changedAt": "2026-09-20T20:21:41.597Z",
  "checkedAt": "2026-09-20T20:21:41.597Z",
  "count": 34,
  "items": [
    {
      "code": "53095",
      "name": "সাদা ভাত,শিং মাছ টমেটো আলু দিয়ে ঝোল,মিক্স সবজি ভাজি,ডাল ভূনা,সালাদ লেবু",
      "chef": "Mst Farzana (Toma)",
      "price": 191,
      "available": 10,
      "images": []
    },
    {
      "code": "54906",
      "name": "সাদা ভাত,সোনালি মোরগ ভূনা,মিক্স সবজি ভাজি,ডাল ভূনা,সালাদ লেবু",
      "chef": "Mst Farzana (Toma)",
      "price": 192,
      "available": 10,
      "images": []
    },
    {
      "code": "67437",
      "name": "সাদা ভাত,শোল মাছ ভুনা,মিক্স সবজি ভাজি,ডাল ভূনা,সালাদ লেবু",
      "chef": "Mst Farzana (Toma)",
      "price": 197,
      "available": 10,
      "images": []
    },
    {
      "code": "62231",
      "name": "সোনালি মুরগি আলু দিয়ে ঝোল, ডিম দিয়ে পেপে ভাজি,পাটশাক ডাল ,ভাত,সালাদ",
      "chef": "Soneka Begum",
      "price": 192,
      "available": 10,
      "images": []
    },
    {
      "code": "66989",
      "name": "টেংরা মাছ টমেটো আলু দিয়ে ঝোল, ডিম দিয়ে পেপে ভাজি,পাটশাক ডাল ,ভাত,সালাদ",
      "chef": "Soneka Begum",
      "price": 171,
      "available": 9,
      "images": []
    },
    {
      "code": "67235",
      "name": "সোনালি মুরগি আলু দিয়ে ভুনা,কচু শাক ভাজি, রুই মাছের মাথা দিয়ে মুগ ডালের মুড়িঘন্ট, ভাত,সালাদ",
      "chef": "Shathi Akter",
      "price": 192,
      "available": 10,
      "images": []
    },
    {
      "code": "67253",
      "name": "চিংড়ি মাছ ভুনা (৩/৪পিস),কচু শাক ভাজি, রুই মাছের মাথা দিয়ে মুগ ডালের মুড়িঘন্ট, ভাত,সালাদ",
      "chef": "Shathi Akter",
      "price": 186,
      "available": 10,
      "images": []
    },
    {
      "code": "70043",
      "name": "আইর মাছ ভুনা,,কচু শাক ভাজি, রুই মাছের মাথা দিয়ে মুগ ডালের মুড়িঘন্ট, ভাত,সালাদ",
      "chef": "Shathi Akter",
      "price": 197,
      "available": 10,
      "images": []
    },
    {
      "code": "67487",
      "name": "দুই রকমের ডাল দিয়ে পোলাও চালের ভুনা খিচুড়ি, সোনালি মুরগির ভুনা, ডিম ভাজি,সালাদ",
      "chef": "labony",
      "price": 213,
      "available": 10,
      "images": []
    },
    {
      "code": "67651",
      "name": "সোনালি মোরগ ভুনা,ভাত,ঘন ডাল, টাকি ভর্তা,সালাদ",
      "chef": "labony",
      "price": 192,
      "available": 19,
      "images": []
    },
    {
      "code": "67983",
      "name": "টমেটো দিয়ে বোয়াল মাছ ভুনা, ভাত,ঘন ডাল, টাকি ভর্তা,সালাদ",
      "chef": "labony",
      "price": 197,
      "available": 10,
      "images": []
    },
    {
      "code": "67842",
      "name": "ডিম ভুনা+সাদা ভাত+ দুই পদের ভর্তা +ডাল+সালাদ।",
      "chef": "Barsha Akhter",
      "price": 161,
      "available": 8,
      "images": []
    },
    {
      "code": "68750",
      "name": "সোনালি মুরগি আলু দিয়ে ঝোল, পেঁপে ভর্তা, কালোজিরা ভর্তা,আলু ভর্তা, আমরা দিয়ে ঘন ডাল, নাজির শাইল চালের ভাত,সালাদ",
      "chef": "Masuma Khatun",
      "price": 192,
      "available": 10,
      "images": []
    },
    {
      "code": "69902",
      "name": "গরুর মাংস আলু দিয়ে ঝোল, কালোজিরা ভর্তা,পেঁপে ভর্তা, আলু ভর্তা,আমরা দিয়ে ডাল,নাজির শাইল চালের ভাত,সালাদ",
      "chef": "Masuma Khatun",
      "price": 224,
      "available": 8,
      "images": []
    },
    {
      "code": "70925",
      "name": "কাইক্কা/ কাকিলা মাছ আলু দিয়ে ভুনা, পেঁপে ভর্তা, কালোজিরা ভর্তা,,আলু ভর্তা , আমরা দিয়ে ডাল,নাজির শাইল চালের ভাত,সালাদ",
      "chef": "Masuma Khatun",
      "price": 171,
      "available": 10,
      "images": []
    },
    {
      "code": "69387",
      "name": "সোনালী মুরগী কষা ঝাল ভুনা আলু দিয়ে,পেঁপে ভাজি,ডাল ভর্তা,ঘন ডাল ভুনা,মোজাম্মেল মিনিকেট ভাত,সালাদ।",
      "chef": "Selina Akhter",
      "price": 191,
      "available": 12,
      "images": []
    },
    {
      "code": "70399",
      "name": "কাচকি মাছের চচ্চড়ি আলু টমেটো দিয়ে,পেঁপে ভাজি,ডাল ভর্তা,ঘন ডাল ভুনা,মোজাম্মেল মিনিকেট ভাত,সালাদ।",
      "chef": "Selina Akhter",
      "price": 181,
      "available": 7,
      "images": []
    },
    {
      "code": "71271",
      "name": "ডাল ভর্তা,ঘন ডাল ভুনা,মোজাম্মেল মিনিকেট ভাত,সালাদ।",
      "chef": "Selina Akhter",
      "price": 201,
      "available": 10,
      "images": []
    },
    {
      "code": "69520",
      "name": "ডিম ভাজা পিঁয়াজ কাঁচামরিচ দিয়ে, আলুর ভর্তা,ঘন ডাল, নাজির চাল এর ভাত",
      "chef": "Tanzima Akther",
      "price": 161,
      "available": 4,
      "images": []
    },
    {
      "code": "71315",
      "name": "গরুর৷ মাথার বা চাপার মাংস দিয়ে বুটের ডাল,আলুর ভর্তা নাজির চাল এর ভাত।",
      "chef": "Tanzima Akther",
      "price": 171,
      "available": 10,
      "images": []
    },
    {
      "code": "71335",
      "name": "দেশি ছোট চিংড়ি ডাটা দিয়ে কারি,আলুর ভর্তা, ডাল,নাজির চাল।",
      "chef": "Tanzima Akther",
      "price": 166,
      "available": 7,
      "images": []
    },
    {
      "code": "70839",
      "name": "রুপচাঁদা মাছ ভুনা+ডিম দিয়ে চিচিঙ্গা ভাজি +ঘন মসুরের ডাল +সাদা ভাত+সালাদ।",
      "chef": "Kamrunnahar",
      "price": 208,
      "available": 8,
      "images": []
    },
    {
      "code": "71334",
      "name": "বেগুন ইলিশ +ডিম দিয়ে চিচিঙ্গা ভাজি +ঘন মসুরের ডাল +সাদা ভাত।",
      "chef": "Kamrunnahar",
      "price": 192,
      "available": 6,
      "images": []
    },
    {
      "code": "71328",
      "name": "নাজির চালের ভুনা খিচুড়ি+সোনালী মুরগি কষা ভুনা+ডিম ভাজা+সালাদ",
      "chef": "Sharmin",
      "price": 203,
      "available": 15,
      "images": []
    },
    {
      "code": "71329",
      "name": "বেগুন আলু টমেটো দিয়ে রুই মাছ+ঘন ডাল +লাউ শাক ভাজি+ভাত+সালাদ",
      "chef": "Sharmin",
      "price": 182,
      "available": 10,
      "images": []
    },
    {
      "code": "71330",
      "name": "টমেটো দিয়ে কাতল মাছ ভুনা+ঘন ডাল+লাল শাক ভাজি+ভাত+সালাদ",
      "chef": "Sharmin",
      "price": 192,
      "available": 5,
      "images": []
    },
    {
      "code": "71331",
      "name": "টমেটো আলু দিয়ে বোয়াল মাছ,, ডাল ভুনা,, বেগুন ভর্তা ,,ভাত ,,সালাত",
      "chef": "Samanta",
      "price": 187,
      "available": 8,
      "images": []
    },
    {
      "code": "71332",
      "name": "সিম আলু দিয়ে কই মাছ,, ডাল ভুনা ,,বেগুন ভর্তা,, ভাত,, সালাত",
      "chef": "Samanta",
      "price": 171,
      "available": 9,
      "images": []
    },
    {
      "code": "71333",
      "name": "ডিম দোপেঁয়াজা,, ডাল ভুনা,, বেগুন ভর্তা ,,ভাত ,,সালাত",
      "chef": "Samanta",
      "price": 155,
      "available": 8,
      "images": []
    },
    {
      "code": "71336",
      "name": "সোনালি মুরগি ভুনা,,,পুইশাক দিয়া ডাল,,,আলু ভর্তা,,,এবং ভাত।",
      "chef": "Amena",
      "price": 192,
      "available": 10,
      "images": []
    },
    {
      "code": "71337",
      "name": "গরু গোস্ত আলু দিয়া জোল,,,আটার রুটি(৪)পিস,,,আলু ভাজি।",
      "chef": "Amena",
      "price": 218,
      "available": 10,
      "images": []
    },
    {
      "code": "71338",
      "name": "সোনালী মুরগি ভুনা, মিক্সড সবজি লইট্টা শুঁটকি দিয়ে, পেঁপে ভর্তা, ডাল, নাজির শাইল চালের ভাত, সালাদ।",
      "chef": "Maymuna Munny",
      "price": 203,
      "available": 10,
      "images": []
    },
    {
      "code": "71339",
      "name": "ডিম ভুনা, মিক্সড সবজি লইট্টা শুঁটকি দিয়ে, পেঁপে ভর্তা, ডাল, নাজির শাইল চালের ভাত, সালাদ।",
      "chef": "Maymuna Munny",
      "price": 176,
      "available": 10,
      "images": []
    },
    {
      "code": "71340",
      "name": "ভুনা খিচুড়ি (নাজির শাইল চালের+মসুর ডাল+মুগ ডাল ), সোনালী মুরগি ভুনা, আলু ভর্তা, বাদাম ভর্তা, সালাদ।",
      "chef": "Maymuna Munny",
      "price": 224,
      "available": 10,
      "images": [
        "static-site/img/location.png",
        "static-site/img/icon-03.png",
        "static-site/img/way.png",
        "static-site/img/app-phn-logo.png",
        "static-site/img/phn.png"
      ]
    }
  ]
};
