// Generated by scripts/scrape-menu.mjs. Do not edit by hand.
window.FOOSTO_MENU = {
  "source": "https://menu.foosto.com/",
  "changedAt": "2026-09-16T20:58:29.864Z",
  "checkedAt": "2026-09-16T23:33:32.549Z",
  "count": 33,
  "items": [
    {
      "code": "52017",
      "name": "সাদা ভাত,রুই মাছ ভুনা,বেগুন ভাজা,ডাল ভুনা,সালাদ লেবু",
      "chef": "Mst Farzana (Toma)",
      "price": 198,
      "available": 10,
      "images": []
    },
    {
      "code": "52683",
      "name": "সাদা ভাত,বোয়াল মাছ ভুনা,বেগুন ভাজা,ডাল ভুনা,সালাদ লেবু",
      "chef": "Mst Farzana (Toma)",
      "price": 203,
      "available": 10,
      "images": []
    },
    {
      "code": "54906",
      "name": "সাদা ভাত,সোনালি মোরগ ভূনা,বেগুন ভাজা,ডাল ভুনা,সালাদ লেবু",
      "chef": "Mst Farzana (Toma)",
      "price": 192,
      "available": 10,
      "images": []
    },
    {
      "code": "62231",
      "name": "সোনালি মুরগি আলু দিয়ে ঝোল , শাকভাজি,ডাটা দিয়ে ইলিশ মাছের মাথা, ভাত,সালাদ",
      "chef": "Soneka Begum",
      "price": 192,
      "available": 10,
      "images": []
    },
    {
      "code": "68073",
      "name": "কাতল মাছ টমেটো দিয়ে ঝোল , শাকভাজি,ডাটা দিয়ে ইলিশ মাছের মাথা, ভাত,সালাদ",
      "chef": "Soneka Begum",
      "price": 182,
      "available": 9,
      "images": []
    },
    {
      "code": "71305",
      "name": "ইলিশ মাছ দোপেয়াজা, শাকভাজি,ডাটা দিয়ে ইলিশ মাছের মাথা, ভাত,সালাদ",
      "chef": "Soneka Begum",
      "price": 208,
      "available": 5,
      "images": []
    },
    {
      "code": "67153",
      "name": "পাবদা মাছ ভুনা, করলা ভাজি,শাক দিয়ে চিংড়ি মাছের তরকারি ,ভাত",
      "chef": "Shathi Akter",
      "price": 168,
      "available": 10,
      "images": []
    },
    {
      "code": "67257",
      "name": "ডিম আলুর তরকারি, করলা ভাজি,শাক দিয়ে চিংড়ি মাছের তরকারি ,ভাত",
      "chef": "Shathi Akter",
      "price": 155,
      "available": 10,
      "images": []
    },
    {
      "code": "67727",
      "name": "কাতলা মাছ টমেটো দিয়ে ভুনা, করলা ভাজি,শাক দিয়ে চিংড়ি মাছের তরকারি ,ভাত",
      "chef": "Shathi Akter",
      "price": 192,
      "available": 10,
      "images": []
    },
    {
      "code": "68750",
      "name": "সোনালি মুরগি আলু দিয়ে ঝোল, ইলিশ মাছের ভর্তা, আলু ভর্তা, পাটশাক দিয়ে ডাল, নাজির শাইল চালের ভাত,সালাদ",
      "chef": "Masuma Khatun",
      "price": 192,
      "available": 9,
      "images": []
    },
    {
      "code": "68992",
      "name": "ইলিশ মাছ বেগুন দিয়ে ঝোল ( ছোট ) , ইলিশ মাছের ভর্তা,আলু ভর্তা , পাটশাক দিয়ে ডাল,নাজির শাইল চালের ভাত,সালাদ",
      "chef": "Masuma Khatun",
      "price": 187,
      "available": 10,
      "images": []
    },
    {
      "code": "70759",
      "name": "কাচকি মাছ আলু টমেটো দিয়ে চচ্চড়ি , ইলিশ মাছের ভর্তা,আলু ভর্তা, পাটশাক দিয়ে ডাল,নাজির শাইল চালের ভাত,সালাদ",
      "chef": "Masuma Khatun",
      "price": 171,
      "available": 8,
      "images": []
    },
    {
      "code": "69364",
      "name": "দেশি পুঁটি মুচমুচে ভাজা, আলুর ভর্তা, গন ডাল, নাজির চাল।",
      "chef": "Tanzima Akther",
      "price": 171,
      "available": 5,
      "images": []
    },
    {
      "code": "69860",
      "name": "আস্ত ডিম ভুনা,,ডাল, আলুর ভর্তা, নাজির চাল।",
      "chef": "Tanzima Akther",
      "price": 161,
      "available": 6,
      "images": []
    },
    {
      "code": "69890",
      "name": "সব্জি খিচুড়ি ডাল, নাজির চাল দিয়ে,ডিম ভুনা,আলু ভর্তা।",
      "chef": "Tanzima Akther",
      "price": 161,
      "available": 7,
      "images": []
    },
    {
      "code": "69387",
      "name": "সোনালী মুরগী কষা ঝাল ভুনা আলু দিয়ে,সুস্বাদু বাদম ভর্তা,চিচিঙ্গা ভাজি ডিম দিয়ে,পাটশাক দিয়ে ঘন ডাল,মোজাম্মেল মিনিকেট ভাত,সালাদ।",
      "chef": "Selina Akhter",
      "price": 191,
      "available": 12,
      "images": []
    },
    {
      "code": "69409",
      "name": "কৈ মাছ ঝোল ভুনা আলু + টমেটো দিয়ে,সুস্বাদু বাদম ভর্তা,ঢেরস ভাজি,পাটশাক দিয়ে ঘন ডাল,মোজাম্মেল মিনিকেট ভাত,সালাদ।",
      "chef": "Selina Akhter",
      "price": 185,
      "available": 10,
      "images": []
    },
    {
      "code": "70830",
      "name": "চিংড়ি মাছ ভুনা ৪/পিচ টমেটো দিয়ে,সুস্বাদু বাদম ভর্তা,ঢেরস ভাজি,পাটশাক দিয়ে ঘন ডাল,মোজাম্মেল মিনিকেট ভাত,সালাদ।",
      "chef": "Selina Akhter",
      "price": 200,
      "available": 12,
      "images": []
    },
    {
      "code": "70802",
      "name": "সোনালী মুরগী মাংস আলু দিয়ে ঝোল , মুজাম্মেল মিনিকেট চালের ভাত, রুই মাছ মাথা দিয়ে মুড়িঘণ্ট ,ঢেঁড়স ভাজি, মাছ দিয়ে পটল ভর্তা , সালাত।",
      "chef": "Sultana Razia",
      "price": 192,
      "available": 15,
      "images": []
    },
    {
      "code": "70829",
      "name": "গরুর মাংস আলু দিয়ে ভুনা, মোজাম্মেল মিনিকে চাউলের ভাত,রুই মাছের মাথা দিয়ে মুড়িঘণ্ট ঢ়েড়স ভাজি , মাছ দিয়ে পটল ভর্তা সালাত।",
      "chef": "Sultana Razia",
      "price": 229,
      "available": 10,
      "images": []
    },
    {
      "code": "70932",
      "name": "বড় চিংড়ি মাছ ভুনা( ৪ পিছ) মোজাম্মেল মিনিকেট চালের ভাত,রুই মাছের মাথা দিয়ে মুড়িঘণ্ট ,মাছ দিয়ে পটল ভর্তা, ঢেঁড়স ভাজি ,সালাত",
      "chef": "Sultana Razia",
      "price": 197,
      "available": 15,
      "images": []
    },
    {
      "code": "71302",
      "name": "নাজির চালের ভুনা খিচুড়ি+হাঁসের মাংস কষা ভুনা+ডিম ভাজা+সালাদ",
      "chef": "Sharmin",
      "price": 266,
      "available": 8,
      "images": []
    },
    {
      "code": "71303",
      "name": "সোনালী মুরগি কষা ভুনা+লাউ দিয়ে মাছের মাথা+পুঁই শাক ভাজি+ভাত+সালাদ",
      "chef": "Sharmin",
      "price": 192,
      "available": 5,
      "images": []
    },
    {
      "code": "71304",
      "name": "টমেটো কাতল মাছ ভুনা+লাউ মাছের মাথা+পুঁই শাক ভাজি+ভাত+সালাদ",
      "chef": "Sharmin",
      "price": 192,
      "available": 7,
      "images": []
    },
    {
      "code": "71306",
      "name": "পোয়া মাছ ভুনা,, চিংড়ি দিয়ে ডাটা,, ডিম দিয়ে চিচিঙ্গা ভাজি,, ভাত,, সালাত",
      "chef": "Samanta",
      "price": 171,
      "available": 7,
      "images": []
    },
    {
      "code": "71307",
      "name": "বড় পাঙ্গাস মাছ ভুনা,, চিংড়ি দিয়ে ডাটা,, ডিম দিয়ে চিচিঙ্গা ভাজি,, ভাত,,",
      "chef": "Samanta",
      "price": 171,
      "available": 5,
      "images": []
    },
    {
      "code": "71308",
      "name": "ডিম তেলানী,,চিংড়ি দিয়ে ডাটা,, ডিম দিয়ে চিচিঙ্গা ভাজি,, ভাত,,সালাত",
      "chef": "Samanta",
      "price": 155,
      "available": 7,
      "images": []
    },
    {
      "code": "71309",
      "name": "প্লেইন পোলাও, সোনালী মুরগি ঝাল রোস্ট, ডিম কোরমা, সালাদ।",
      "chef": "Maymuna Munny",
      "price": 266,
      "available": 10,
      "images": []
    },
    {
      "code": "71313",
      "name": "প্লেইন পোলাও,গরুর গোশত আলু দিয়ে ভুনা, সোনালী মুরগি রোস্ট, সালাদ।",
      "chef": "Maymuna Munny",
      "price": 287,
      "available": 5,
      "images": []
    },
    {
      "code": "71314",
      "name": "ভুনা খিচুড়ি ( নাজির শাইল চাল+মসুর ডাল+মুগ ডাল) গরুর গোশত আলু দিয়ে ভুনা, আচার, বাদাম+কালো জিরা ভর্তা, সালাদ।",
      "chef": "Maymuna Munny",
      "price": 245,
      "available": 5,
      "images": []
    },
    {
      "code": "71310",
      "name": "সোনালি মুরগি কষা ভুনা,মিষ্টি কুমরা শাক চিংড়ী মাছ দিয়া জোল,ভর্তা এবং ভাত।",
      "chef": "Amena",
      "price": 192,
      "available": 10,
      "images": []
    },
    {
      "code": "71311",
      "name": "আটার রুটি (৪)পিস,,,সোনালি মুরগি কষা ভুনা,,,বুটের ডাল ভুনা।",
      "chef": "Amena",
      "price": 189,
      "available": 10,
      "images": []
    },
    {
      "code": "71312",
      "name": "ডিম ভুনা,,,মিষ্টি কুমরা সাক চিংড়ী দিয়া জোল,,,বেগুন ভর্তা,,,এবং ভাত।",
      "chef": "Amena",
      "price": 171,
      "available": 10,
      "images": [
        "static-site/img/location.png",
        "static-site/img/icon-03.png",
        "static-site/img/way.png",
        "static-site/img/app-phn-logo.png",
        "static-site/img/phn.png"
      ]
    }
  ]
};
